### ISSUE TITLE
PowerVu Support

### ISSUE THREAD

**Issue by joeusercz** [bas-t/descrambler#1]
Hello Tycho, first of all thank you very much for your work on this. I was a sasc-ng user many years ago, but only recently dusted off my old Skystar2 pci card (dvb-s only) to play with. I am sure you are familiar with the oscam-emu patch for oscam and probably know they have implemented a method for descrambling powervu. But, their method includes a hack of using a stream relay. I am interested in a better solution and I think that your descrambler (and dvbloopback) could be the best way to do that. Since I am not that great of a programmer, and you know your code best, I would like to ask if you have any interest in adding powervu to the list of systems descrambler handles? I am currently using ffdecsawrapper (because I am using a stock Wheezy installation and kernel) but I can certainly update my kernel if needed for testing. If you don't have interest and/or time, can you give me some pointers on where I should begin to attempt it on my own?
Also, I read in an older issue with ffdescrambler when someone asked about a forum for support, that you did not know of one. Has that changed?

**Comment by bas-t** [comment]
Op 21-07-15 om 22:44 schreef joeusercz:

> Hello Tycho, first of all thank you very much for your work on this. I 
> was a sasc-ng user many years ago, but only recently dusted off my old 
> Skystar2 pci card (dvb-s only) to play with. I am sure you are 
> familiar with the oscam-emu patch for oscam and probably know they 
> have implemented a method for descrambling powervu.
> 
> No, I'm not aware of that. I only use DVB-C and that's where it ends. 
> And I've never stumbled on powervu either. Those things are way beyond 
> my focus (beeing keep my setup valid for all future kernels). You have 
> to realise that while I publish all of my work, so that other people can 
> use it too, I think of my repo's primary as my personal playground.
> 
> But, their method includes a hack of using a stream relay. I am 
> interested in a better solution and I think that your descrambler (and 
> dvbloopback) could be the best way to do that. Since I am not that 
> great of a programmer, and you know your code best, I would like to 
> ask if you have any interest in adding powervu to the list of systems 
> descrambler handles? I am currently using ffdecsawrapper (because I am 
> using a stock Wheezy installation and kernel) but I can certainly 
> update my kernel if needed for testing. If you don't have interest 
> and/or time, can you give me some pointers on where I should begin to 
> attempt it on my own?
> 
> I don't have any interest in adding powervu. And since I don't know 
> anything about powervu, I can't give you any pointers.
> 
> Also, I read in an older issue with ffdescrambler when someone asked 
> about a forum for support, that you did not know of one. Has that changed
> 
> Sadly, no.

**Comment by joeusercz** [comment]
Thanks for the quick reply. I was not aware that you only worked with dvb-c. I do understand the work is for you and you are sharing, and we do appreciate that. I will give it a try myself then.
