### ISSUE TITLE
ffdecsawrapper tuning issue

### ISSUE THREAD

**Issue by thex-at** [bas-t/descrambler#15]
Hi,
i have a problem with ffdecsawrapper since i upgraded my MythTV system to Ubuntu 16.04LTS...
On all my three Hauppauge NovaS2 cards ffdecsawrapper works fine and as expected but after a while on one of the cards tuning hangs with (TL__) and the recordings fail.

The other two cards still work fine and the only thing i can do to fix this is to restart ffdecsawrapper.

After restarting ffdecsawrapper all three tuners are fine again until one of them shows the issue again. It does not matter what channel the card tries to tune to and also the adapter having the issue changes...

Did someone ever experience similar issues? Any hint would be highly appreciated...

Thanks!

**Comment by bas-t** [comment]
Don't have a clue. And since nobody else seems to have one, I'm closing this ticket.
