### ISSUE TITLE
ffdecsawrapper segfaults

### ISSUE THREAD

**Issue by wslegend** [bas-t/descrambler#4]
Hello,

It's me again. I'm using the mainline cx24120 drivers with Kernel 4.3 now. Until yesterday i have used 4.3.0 and everything worked fine. But after upgrading to 4.3.3 today ffdecsawrapper segfaults again and i don't know why :(

ffdecsa log:
http://pastebin.com/raw/BeVWeddm

backtrace:
http://pastebin.com/raw/vGac7bvG

I had the same problem with 4.3.0 but it magically disappeared after some reboots... Do you have any clue what could cause this?

DVB-S2 Card:  Technisat SkyStar2
Distribution: Archlinux

cheers

**Comment by bas-t** [comment]
First of all, please use the stable branch of descrambler.

Second: how did you compile the dvbloopback kernel module? The backtrace complains about the lack of symbol table info, so I guess something went wrong there.

**Comment by wslegend** [comment]
It works with the stable branch .. Sorry for wasting your time :/

Anyway:
I have added the following lines to my kernel PKGBUILD:

```
mkdir drivers/media/pci/dvbloopback
cp -f ${srcdir}/dvbloopback/dvbloopback/* drivers/media/pci/dvbloopback/
patch -p1 < ${srcdir}/dvbloopback/dvbloopback.patch
patch -p0 < ${srcdir}/dvbloopback/3.13-dvb-core.patch

echo "CONFIG_DVB_LOOPBACK_ADAPTER=m" >> ./.config
sed -i "s/CONFIG_MEDIA_CONTROLLER_DVB=y/# CONFIG_MEDIA_CONTROLLER_DVB is not set/" ./.config
```

The patches are applied correctly.

**Comment by bas-t** [comment]
Your PKGBUILD looks perfect to me.

Cheers,
Tycho.
